version: "3.8"

services:
  backend:
    container_name: backend-dev
    image: backend-dev
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
  frontend:
    container_name: frontend-dev
    image: frontend-dev
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000